"""
Generate a cohort of synthetic users with EMA, Heart rate, timestamp and unique uuid. 
- Generator can tweak response rate to simulate 'No Reponse' to EMAs 
- Current dataframe format is not suited to store in database!

Author: @tylerrleee
Date: 05/31/2026
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
import matplotlib.dates as mdates
import uuid

### EMA GENERATOR 
def generate_user_ids(n_users):
    """Generates a list of n_users strings, each being a unique UUID"""
    return [str(uuid.uuid4()) for _ in range(n_users)]

def generate_user(user_id,
                  days,
                  ema_per_day,
                  rng,
                  resp_rate=0.80,
                  mean_gap_length = 3,
                  mu=None,
                  sigma=None,
                  rho=None):
    """

    Generate one user's EMA series with KNOWN latent volatility.
    Assumes sample is normally distributed

    mu / sigma / rho may be passed explicitly to assign a *known* latent
    volatility (used by the MSSD validation harness to build Stable vs.
    Volatile cohorts). When left as None they are drawn at random, preserving
    the original per-user behaviour.
    """

    n = days * ema_per_day

    # per-user latent parameters (ground truth for the population).
    # Drawn at random unless the caller pins them to a known value.
    if mu is None:
        mu = rng.uniform(2.0, 4.0)
    if sigma is None:
        sigma = rng.uniform(0.3, 1.5) # How volatile a person is (0 means they are exactly at the mean)
    if rho is None:
        rho = rng.uniform(0.1, 0.8) # personal correlation

    # AR(1)  -- consecutive points are related
    # lambda^2 = E[(x_{i+1} - x_i)^2] = 2\sigma^2(1-p(1))
    

    z = np.zeros(n)
    z[0] = rng.normal(0, sigma) # define mean, and std (degree of spread)
    for t in range(1, n):
      z[t] = rho * z[t-1] + rng.normal(0, sigma * np.sqrt(1 - rho**2))
    latent = mu + z

    # map latent to Likert response
    ema = np.clip(np.round(latent), 1, 5)
  
    mask = _clustered_missing_mask(n, resp_rate, mean_gap_length, rng) # bool mask
    ema[mask] = np.nan
    
    expected_mssd = 2.0 * sigma**2 * (1 - rho) # ground truth
    timestamps = pd.date_range(start="2026-06-01", periods=n, freq="min")

    return pd.DataFrame({
        "user_id": user_id,
        "timestamp": timestamps,
        "prompt_idx": np.arange(n),
        "day": np.arange(n) // ema_per_day,
        "ema": ema,
        "true_sigma": sigma,
        "true_rho": rho,
        "true_expected_mssd": expected_mssd,
    })

  
def _clustered_missing_mask(n, resp_rate, mean_gap_length, rng):
    """
    Boolean mask of length n where True = missing (NaN), generated by a
    two-state Markov chain so that missingness arrives in clusters.

    resp_rate        : fraction of prompts answered (missing rate m = 1 - resp_rate)
    mean_gap_length  : average length of a missing run, in prompts (>= 1)
    rng              : np.random.Generator

    The long-run missing rate is m regardless of clustering; mean_gap_length
    only controls how the misses are clumped.
    """

    missing_rate = 1.0 - resp_rate

    if missing_rate <= 0.0:
      return np.zeros(n, dtype=bool) # nobody miss answering
    
    elif missing_rate >= 1.0:
      return np.ones(n, dtype=bool) # everything misses
    
    if mean_gap_length < 1.0:
      raise ValueError("mean_gap_length must be >= 1")
    
    # transition probabilities
    b = 1.0 / mean_gap_length # P(missing -> responding): ending a gap
    a = missing_rate * b / (1.0 - missing_rate) # P(responding -> missing) [0,1] starts a gap

    # feasiability
    if a > 1.0:
        raise ValueError(
            f"infeasible combo: mean_gap_length {mean_gap_length:.2f} with mean gap "
            f"{mean_gap_length} needs P(start gap) = {a:.2f} > 1. "
            f"lower the missing rate or allow longer gaps."
        )
    mask = np.zeros(n, dtype=bool)
    missing = rng.random() < missing_rate
    mask[0] = missing
    for t in range(1, n):
      if missing:
        missing = rng.random() >= b # stay missing
      
      else:
        missing = rng.random() < a # start a gap w/ P(responding -> missing)
      
      mask[t] = missing
    
    return mask
    
def generate_cohort(users = 100,
                    days  = 14,
                    ema_per_day = 5,
                    seed = 0,
                    resp_rate = 0.8,
                    mean_gap_length = 3,
                    user_ids = None,
                    mu = None,
                    sigma = None,
                    rho = None):

    if users < 1:
      raise ValueError(f"Need more than one user to generate... got {users}")
    if days < 1:
      raise ValueError(f"Need more than one day to generate... got {days}")
    if ema_per_day < 1:
      raise ValueError(f"Need more than one day to generate... got {ema_per_day}")
    if resp_rate > 1 or resp_rate < 0:
      raise ValueError(f"Need RESPONSE RATE within range [0,1]... got {resp_rate}")

    if user_ids is None:
      user_ids = generate_user_ids(users)
    rng = np.random.default_rng(seed)
    all_data = []

    for uid in user_ids:
        df_user = generate_user(user_id = uid,
                                days = days,
                                ema_per_day = ema_per_day,
                                rng = rng,
                                resp_rate = resp_rate,
                                mean_gap_length = mean_gap_length,
                                mu = mu,
                                sigma = sigma,
                                rho = rho)
        all_data.append(df_user)

    return pd.concat(all_data)

### WEARABLE PROFILE
# We simulate the Garmin hardware line (Venu 3 / Vivoactive 5/6) rather than
# Fitbit. Garmin reports two distinct HRV-based products:
#   - all-day STRESS (0-100): continuous, reported minute-by-minute. Modelled
#     here directly from heart rate (see `_generate_stress`).
#   - HRV STATUS: OVERNIGHT only -- RMSSD is measured during sleep, one value
#     per night, compared against a rolling 7-day baseline to label a status
#     (Balanced / Unbalanced / Low). Modelled nightly (see `generate_HRV`),
#     NOT continuously coupled to heart rate.
GARMIN_DEVICES = ("Garmin Venu 3", "Garmin Vivoactive 5", "Garmin Vivoactive 6")


def _generate_stress(hr,
                     rng,
                     stress_window = (55.0, 130.0),
                     stress_noise_std = 4.0):
    """
    Continuous minute-level Garmin-style stress score (0-100) derived directly
    from heart rate: higher HR (arousal / exertion) reads as higher stress.

    HR is normalised over a resting->exertion band and mapped onto 0-100. Because
    the activity bouts already live in the HR trace, exercise spikes naturally
    produce stress spikes -- without routing through HRV (which is overnight-only
    on Garmin and modelled separately).

    Args:
        hr               : 1D array of minute-level heart rate (bpm).
        rng              : np.random.Generator.
        stress_window    : (lo, hi) HR band normalised onto the 0-100 score.
        stress_noise_std : std of additive stress noise (points).

    Returns:
        stress float array, same length as `hr`.
    """
    hr = np.asarray(hr, dtype=float)
    lo, hi = stress_window
    norm = np.clip((hr - lo) / (hi - lo), 0.0, 1.0)
    stress = 100.0 * norm + rng.normal(0, stress_noise_std, hr.shape[0])
    return np.clip(stress, 0.0, 100.0)


def _generate_continuous_hrv(hr_minute,
                             rng,
                             resting_hr,
                             base_rr_sd = 30.0,
                             rr_sd_clip = (3.0, 150.0),
                             rmssd_clip = (3.0, 200.0)):
    """
    Beat-by-beat RR simulation -> continuous (all-day) HRV.

    A Garmin device measures inter-beat (RR) intervals continuously and recovers
    instantaneous heart rate as 60000 / RR. From the RR series it derives HRV
    (RMSSD = root mean square of successive RR differences). Unlike the
    overnight-only HRV Status in `generate_HRV`, this is an ALL-DAY trace.

    We treat the minute-level mean HR as the target rhythm: minute m emits about
    `hr_minute[m]` beats whose mean RR is 60000 / hr_minute[m]. Beat-to-beat RR
    jitter (the source of HRV) shrinks as HR climbs above rest -- parasympathetic
    withdrawal during exertion -- so its per-minute SD is scaled by
    resting_hr / hr_minute. RMSSD is then summarised per minute.

    Args:
        hr_minute   : 1D minute-level mean heart rate (bpm) -- the target rhythm.
        rng         : np.random.Generator.
        resting_hr  : per-user baseline bpm; the high-HRV (rest) anchor.
        base_rr_sd  : beat-to-beat RR SD (ms) at resting HR. Single tuning knob;
                      RMSSD at rest is ~sqrt(2) * base_rr_sd.
        rr_sd_clip  : physiological clip on the per-minute RR SD (ms).
        rmssd_clip  : physiological clip on the per-minute RMSSD (ms).

    Returns:
        (rmssd_ms, hr_from_rr): two length-len(hr_minute) float arrays --
        continuous RMSSD per minute, and BPM recovered from RR per minute (a
        60000 / RR sanity trace that should track `hr_minute` closely).
    """
    hr_minute = np.asarray(hr_minute, dtype=float)
    n_min = hr_minute.shape[0]

    # ~hr beats land in a one-minute window; always at least one.
    counts = np.clip(np.rint(hr_minute).astype(np.intp), 1, None)

    mean_rr_min = 60000.0 / hr_minute                       # ms, per minute
    rr_sd_min = np.clip(base_rr_sd * (resting_hr / hr_minute),
                        rr_sd_clip[0], rr_sd_clip[1])        # HRV shrinks w/ HR

    # expand minute-level quantities to one entry per beat
    mean_rr_beat = np.repeat(mean_rr_min, counts)
    rr_sd_beat   = np.repeat(rr_sd_min, counts)
    minute_id    = np.repeat(np.arange(n_min), counts)

    rr = mean_rr_beat + rng.normal(0.0, 1.0, mean_rr_beat.shape[0]) * rr_sd_beat
    rr = np.clip(rr, 300.0, 2000.0)                          # 30-200 bpm guard

    bpm_beat = 60000.0 / rr                                  # recover BPM from RR

    # per-minute segment starts in the beat array (counts >= 1 -> all non-empty)
    starts = np.zeros(n_min, dtype=np.intp)
    np.cumsum(counts[:-1], out=starts[1:])

    # recovered HR per minute = mean instantaneous BPM
    hr_from_rr = np.add.reduceat(bpm_beat, starts) / counts

    # squared successive RR differences, with cross-minute boundaries zeroed so
    # RMSSD is computed strictly within each minute. Pad to beat length so the
    # final segment start is always valid for reduceat.
    d2 = np.zeros(rr.shape[0])
    diff_rr = np.diff(rr)
    same_min = minute_id[1:] == minute_id[:-1]
    d2[:-1] = np.where(same_min, diff_rr * diff_rr, 0.0)

    sum_d2 = np.add.reduceat(d2, starts)
    pair_counts = counts - 1                                 # within-minute pairs
    with np.errstate(invalid="ignore", divide="ignore"):
        msd = np.where(pair_counts > 0, sum_d2 / pair_counts, np.nan)
    rmssd_ms = np.sqrt(msd)
    # single-beat minutes have no successive pair -> floor for a continuous trace
    rmssd_ms = np.clip(np.nan_to_num(rmssd_ms, nan=rmssd_clip[0]), *rmssd_clip)

    return rmssd_ms, hr_from_rr


### HRV STATUS (overnight)
HRV_STATUS_NO_DATA = "No Status"


def _hrv_status(rmssd, baseline_7d, band):
    """
    Garmin-style HRV Status label for one night.

    `baseline_7d` / `band` are NaN until enough history has accrued, in which
    case the status is "No Status" (Garmin needs a warm-up window). Otherwise
    last night is compared against the personalised baseline band:
        within band -> Balanced;  below -> Low;  above -> Unbalanced.
    """
    if np.isnan(baseline_7d) or np.isnan(band):
        return HRV_STATUS_NO_DATA
    if rmssd < baseline_7d - band:
        return "Low"
    if rmssd > baseline_7d + band:
        return "Unbalanced"
    return "Balanced"


def _generate_overnight_hrv(days,
                            rng,
                            baseline,
                            daily_load = None,
                            phi = 0.5,
                            night_sd = 6.0,
                            load_coef = 5.0,
                            extra_noise_std = 2.0,
                            rmssd_clip = (15.0, 120.0)):
    """
    One user's overnight average RMSSD (ms) for each of `days` nights.

    Model (NOT tied minute-to-minute to HR):
      - per-user `baseline` overnight RMSSD.
      - night-to-night AR(1) drift: z[d] = phi*z[d-1] + N(0, night_sd*sqrt(1-phi^2)).
      - daily-load coupling: if `daily_load` (per-night z-scored load) is given,
        subtract load_coef * load_z[d] so a hard/stressful day lowers that
        night's recovery.

    Returns a length-`days` float array, clipped to a physiological range.
    """
    z = np.zeros(days)
    z[0] = rng.normal(0, night_sd)
    innov = night_sd * np.sqrt(1.0 - phi ** 2)
    for d in range(1, days):
        z[d] = phi * z[d - 1] + rng.normal(0, innov)

    rmssd = baseline + z + rng.normal(0, extra_noise_std, days)
    if daily_load is not None:
        rmssd = rmssd - load_coef * np.asarray(daily_load, dtype=float)

    return np.clip(rmssd, *rmssd_clip)


### HEART RATE GENERATOR
def _generate_heart_rate(user_id,
                        days,
                        rng,
                        resting_hr = None,
                        hr_range = (60, 100),
                        circadian_amp = 6.0,
                        noise_std = 2.0,
                        bouts_per_day = (0, 3),
                        bout_minutes = (20, 60),
                        bout_intensity = (15, 40),
                        source = "Garmin Venu 3"):
    """
      Minute-level synthetic heart rate for one user over `days` days.

      Args:
        resting_hr : per-user baseline (drawn if None, so users differ). Also
                     anchors the continuous HRV amplitude (high HRV at rest).
        circadian  : daily rhythm, lowest ~4am, highest ~4pm
        noise      : minute-to-minute white noise (see note on AR(1) below)
        bouts      : random activity spikes (count/time/length/size all vary)

      Returns long-format DataFrame: user_id, timestamp, minute, day, hr,
      stress, rmssd_ms, hr_from_rr, source. The minute-level `hr` is the target
      rhythm; `rmssd_ms` is continuous (all-day) HRV and `hr_from_rr` is BPM
      recovered from the simulated RR intervals (60000 / RR) -- see
      `_generate_continuous_hrv`.
    """

    # Build time-series
    min_per_day = 24 * 60
    n = days * min_per_day
    t = np.arange(n)

    # assuming our samples are just young adults
    # 18-24 years old
    # https://my.clevelandclinic.org/health/diagnostics/heart-rate
    if resting_hr is None:
        resting_hr = rng.uniform(*hr_range)
    
    minute_of_day = t % min_per_day
    circadian = -circadian_amp * np.cos(2*np.pi*(minute_of_day - 240) / min_per_day)

    noise = rng.normal(0, noise_std, n)

    activity = np.zeros(n)
    for day in range(days):
        for _ in range(rng.integers(bouts_per_day[0], bouts_per_day[1] + 1)):
            duration = int(rng.integers(*bout_minutes))
            start    = day * min_per_day + int(rng.integers(0, min_per_day - duration))
            activity[start: start + duration] += rng.uniform(*bout_intensity)

    hr = np.clip(resting_hr + circadian + noise + activity, 40, 200)

    # Continuous all-day Garmin stress, derived directly from the HR trace.
    # (HRV Status is overnight-only and generated separately -- see generate_HRV.)
    stress = _generate_stress(hr, rng)

    # Continuous all-day HRV from beat-by-beat RR intervals; also recovers BPM
    # via 60000 / RR as a sanity trace (hr_from_rr ~ hr).
    rmssd_ms, hr_from_rr = _generate_continuous_hrv(hr, rng, resting_hr)

    timestamps = pd.date_range(start="2026-06-01", periods=n, freq="min")
    return pd.DataFrame({
            "user_id":    user_id,
            "timestamp":  timestamps,
            "minute":     t,
            "day":        t // min_per_day,
            "hr":         hr,
            "stress":     stress,
            "rmssd_ms":   rmssd_ms,
            "hr_from_rr": hr_from_rr,
            "source":     source,
        })

def generate_HR(users = 100,
                days  = 14,
                seed = 0,
                heart_rate = None,
                user_ids = None):

    if users < 1:
      raise ValueError(f"Need more than one user to generate... got {users}")
    if days < 1:
        raise ValueError(f"Need more than one day to generate... got {days}")

    if user_ids is None:
      user_ids = generate_user_ids(users)
    rng = np.random.default_rng(seed)

    # Generate data for all users and concatenate. Each user is assigned a
    # Garmin device model so the `source` flag varies across the cohort.
    all_data = []
    for uid in user_ids:
        source = GARMIN_DEVICES[rng.integers(0, len(GARMIN_DEVICES))]
        df_user = _generate_heart_rate(user_id=uid, days=days, rng=rng,
                                       resting_hr=heart_rate, source=source)
        all_data.append(df_user)

    return pd.concat(all_data, ignore_index = True)


def daily_load_from_hr(hr_df):
    """
    Per-user, per-day load proxy for HRV coupling: the day's mean continuous
    stress, z-scored within each user. A high-load day -> positive load_z ->
    lower overnight RMSSD that night (see `_generate_overnight_hrv`).

    Returns a tidy DataFrame: user_id, day, load_z.
    """
    g = (hr_df.groupby(["user_id", "day"])["stress"]
              .mean().reset_index(name="load"))

    def _z(s):
        sd = s.std()
        return (s - s.mean()) / (sd if sd and sd > 0 else 1.0)

    g["load_z"] = g.groupby("user_id")["load"].transform(_z)
    return g[["user_id", "day", "load_z"]]


def generate_HRV(users = 100,
                 days  = 14,
                 seed = 0,
                 user_ids = None,
                 daily_load_df = None,
                 baseline_range = (35.0, 75.0)):
    """
    Nightly Garmin HRV Status for a cohort: one overnight RMSSD per user per
    night, a trailing 7-night baseline, and a status label.

    `daily_load_df` (from `daily_load_from_hr`) optionally couples each night's
    recovery to that day's load. Returns a tidy DataFrame:
        user_id, night, overnight_avg_rmssd, baseline_7d, hrv_status, source.
    """
    if users < 1:
        raise ValueError(f"Need more than one user to generate... got {users}")
    if days < 1:
        raise ValueError(f"Need more than one day to generate... got {days}")

    if user_ids is None:
        user_ids = generate_user_ids(users)
    rng = np.random.default_rng(seed)

    # per-user ordered load array, aligned to day index
    load_lookup = {}
    if daily_load_df is not None:
        for uid, g in daily_load_df.groupby("user_id"):
            load_lookup[uid] = g.sort_values("day")["load_z"].to_numpy()

    start = pd.to_datetime("2026-06-01")
    nights = [start + pd.Timedelta(days=d) for d in range(days)]

    all_rows = []
    for uid in user_ids:
        source = GARMIN_DEVICES[rng.integers(0, len(GARMIN_DEVICES))]
        baseline = rng.uniform(*baseline_range)

        load = load_lookup.get(uid)
        if load is not None and len(load) >= days:
            load = load[:days]
        elif load is not None:                       # pad short series with 0
            load = np.concatenate([load, np.zeros(days - len(load))])

        rmssd = _generate_overnight_hrv(days, rng, baseline, daily_load=load)

        # trailing 7-night baseline + band (excludes the current night so a
        # night is never compared against itself)
        s = pd.Series(rmssd)
        base = s.rolling(window=7, min_periods=3).mean().shift(1)
        std  = s.rolling(window=7, min_periods=3).std().shift(1)
        band = np.maximum(0.5 * std, 5.0)

        status = [_hrv_status(rmssd[d], base.iloc[d], band.iloc[d])
                  for d in range(days)]

        all_rows.append(pd.DataFrame({
            "user_id": uid,
            "night": nights,
            "overnight_avg_rmssd": np.round(rmssd, 1),
            "baseline_7d": np.round(base.to_numpy(), 1),
            "hrv_status": status,
            "source": source,
        }))

    return pd.concat(all_rows, ignore_index=True)

