"""
Single-user JITAI dashboard 
     generates one synthetic participant's
    data and displays all three streams: 
    EMA, Garmin telemetry, and JITAI decisions.

streamlit run single_user_dashboard.py
"""

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

# Resolve syntheticData modules the same way the sensitivity-analysis notebook does.
_REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_REPO_ROOT / "syntheticData"))
sys.path.insert(0, str(_REPO_ROOT / "syntheticData" / "decision"))

from synthetic_generator import (
    generate_cohort,
    generate_HR,
    generate_HRV,
    generate_user_ids,
    daily_load_from_hr,
)
from decision_engine import calculate_mssd, apply_decision_rules
from mssd_validation import recover_ar1_params, empirical_mssd
from run_decision_engine import spread_ema_timestamps

# Sensitivity-grid lookup (from notebook, resp_rate=0.80)
# Rows: threshold quantile 0.70–0.90; Cols: burn-in 0–7 days
# Used to show projected vs actual prompts/week in the overview.
_GRID = {
    0.70: {0: 6.90, 1: 7.10, 2: 7.08, 3: 6.83, 5: 6.51, 7: 6.47},
    0.75: {0: 5.72, 1: 5.89, 2: 5.92, 3: 5.68, 5: 5.39, 7: 5.43},
    0.80: {0: 4.72, 1: 4.85, 2: 4.85, 3: 4.62, 5: 4.35, 7: 4.33},
    0.85: {0: 4.00, 1: 4.10, 2: 4.07, 3: 3.84, 5: 3.56, 7: 3.57},
    0.90: {0: 3.15, 1: 3.21, 2: 3.15, 3: 2.88, 5: 2.71, 7: 2.70},
}

def _grid_projection(threshold_q: float, burn_in: int) -> float:
    """Nearest cell from the sensitivity grid at resp_rate=0.80."""
    tq = min(_GRID.keys(), key=lambda k: abs(k - threshold_q))
    bd = min(_GRID[tq].keys(), key=lambda k: abs(k - burn_in))
    return _GRID[tq][bd]


# Data generation (cached per parameter set)

@st.cache_data(show_spinner="Generating synthetic data…")
def generate_single_user(
    resp_rate: float,
    threshold_q: float,
    burn_in: int,
    seed: int,
    days: int,
    ema_per_day: int,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    uid = generate_user_ids(1)

    ema_df = generate_cohort(
        users=1, days=days, ema_per_day=ema_per_day,
        seed=seed, resp_rate=resp_rate, user_ids=uid,
    )
    ema_df = spread_ema_timestamps(ema_df, ema_per_day)

    hr_df = generate_HR(users=1, days=days, seed=seed, user_ids=uid)
    load_df = daily_load_from_hr(hr_df)
    hrv_df = generate_HRV(
        users=1, days=days, seed=seed,
        user_ids=uid, daily_load_df=load_df,
    )

    dec_df = calculate_mssd(ema_df, window=3)
    dec_df = apply_decision_rules(
        dec_df,
        threshold_quantile=threshold_q,
        cooldown_minutes=60,
        max_prompts_per_day=4,
    )

    return ema_df, hr_df, hrv_df, load_df, dec_df


# Synthetic user profile builder

_FIRST_NAMES = ["Alex", "Jordan", "Casey", "Riley", "Morgan",
                "Taylor", "Blake", "Avery", "Drew", "Skyler"]
_LAST_NAMES  = ["Smith", "Johnson", "Williams", "Brown", "Jones",
                "Garcia", "Miller", "Davis", "Wilson", "Martinez"]
_GENDERS     = ["Male", "Female", "Non-binary", "Prefer not to say"]

def build_user_profile(
    user_id: str,
    seed: int,
    hr_df: pd.DataFrame,
    hrv_df: pd.DataFrame,
) -> dict:
    """Generate a consistent synthetic user record matching the app schema
    (push_token and password excluded — not generated by the simulator)."""
    rng = np.random.default_rng(seed)
    first  = _FIRST_NAMES[int(rng.integers(0, len(_FIRST_NAMES)))]
    last   = _LAST_NAMES[int(rng.integers(0, len(_LAST_NAMES)))]
    gender = _GENDERS[int(rng.integers(0, len(_GENDERS)))]
    age    = int(rng.integers(18, 25))  # UF undergrad range
    birth_year  = 2026 - age
    birth_month = int(rng.integers(1, 13))
    birth_day   = int(rng.integers(1, 29))
    email  = f"{first.lower()}.{last.lower()}{seed % 100:02d}@ufl.edu"

    device_source = hr_df["source"].iloc[0] if not hr_df.empty else "Unknown"
    last_synced   = pd.to_datetime(hr_df["timestamp"]).max() if not hr_df.empty else pd.NaT
    labfront_id   = f"LF-{abs(hash(user_id)) % 10_000_000:07d}"

    # Estimate resting HR as the 5th-percentile of minute-level HR
    resting_hr_est = round(float(np.percentile(hr_df["hr"], 5)), 1) if not hr_df.empty else None

    # Overnight RMSSD baseline (first non-NaN baseline_7d, or mean of available nights)
    baseline_rmssd = hrv_df["baseline_7d"].dropna()
    baseline_rmssd_val = round(float(baseline_rmssd.mean()), 1) if not baseline_rmssd.empty else None

    return {
        "user_id":              user_id,
        "email":                email,
        "first_name":           first,
        "last_name":            last,
        "birthdate":            f"{birth_year}-{birth_month:02d}-{birth_day:02d}",
        "gender":               gender,
        "is_enrolled":          True,
        "enrolled_at":          "2026-06-01 00:00:00",
        # wearable_device fields
        "labfront_participant_id": labfront_id,
        "device_model":         device_source,
        "device_is_active":     True,
        "last_synced_at":       str(last_synced)[:19] if pd.notna(last_synced) else "—",
        # latent simulation parameters (ground-truth, not in real schema)
        "sim_resting_hr_est":   resting_hr_est,
        "sim_baseline_rmssd":   baseline_rmssd_val,
    }


st.set_page_config(
    page_title="JITAI : Synthetic User Simulation",
    page_icon="🩺",
    layout="wide",
)


st.sidebar.header("Simulation parameters")

days = st.sidebar.slider(
    "Study duration (days)",
    min_value=7, max_value=28, value=7, step=1,
)
ema_per_day = st.sidebar.slider(
    "EMA prompts per day",
    min_value=1, max_value=5, value=5, step=1,
    help="Max 5 — prompt times are fixed at 9 am, 12 pm, 3 pm, 6 pm, 9 pm.",
)
resp_rate = st.sidebar.slider(
    "EMA response rate",
    min_value=0.50, max_value=0.95, value=0.80, step=0.05,
    format="%.2f",
)
threshold_q = st.sidebar.slider(
    "MSSD threshold percentile",
    min_value=0.70, max_value=0.90, value=0.80, step=0.05,
    format="%.2f",
)
burn_in = st.sidebar.slider(
    "Burn-in days (no prompts)",
    min_value=0, max_value=days, value=0, step=1,
)
seed = int(st.sidebar.number_input("Random seed", value=42, step=1))

if resp_rate < 0.70:
    st.sidebar.warning(
        "Below 70% response rate: ρ recovery degrades significantly "
        "(ANOVA p < 0.001 in sensitivity analysis)."
    )

with st.sidebar.expander("Generator limitations"):
    st.markdown(
        """
1. **No game-day events** - HR/stress have no structured spikes; activity bouts
   are uniformly random across the day.
2. **Fixed EMA times** - prompts always at 9 am, 12 pm, 3 pm, 6 pm, 9 pm.
   No personalization or adaptive scheduling.
3. **Markov-chain missingness** - non-response gaps are self-correlated but not
   driven by time-of-day, stress level, or events.
4. **HR and JITAI are decoupled** - the engine fires on EMA-MSSD only.
   `hr_at_trigger` / `stress_at_trigger` in the real schema are not yet used.
5. **Overnight HRV is a separate process** - not derived from minute-level HR;
   reacts to daily load with a 1-day lag.
6. **Fixed circadian phase** - HR trough at 4 am, peak at 4 pm for all users.
   No chronotype variation.
7. **No confounders** - illness, travel, sleep deprivation, menstrual cycle
   effects are absent.
        """
    )

# ---------------------------------------------------------------------------
# Generate data
# ---------------------------------------------------------------------------

ema_df, hr_df, hrv_df, load_df, dec_df = generate_single_user(
    resp_rate, threshold_q, burn_in, seed, days, ema_per_day
)

# Derived scalars
true_sigma = float(ema_df["true_sigma"].iloc[0])
true_rho = float(ema_df["true_rho"].iloc[0])
true_mssd = float(ema_df["true_expected_mssd"].iloc[0])

answered = ema_df["ema"].dropna().to_numpy()
rho_hat, sigma_hat = recover_ar1_params(answered)
emp_mssd = empirical_mssd(answered)

n_sent = len(dec_df)
n_responded = int(dec_df["ema"].notna().sum())
actual_rr = n_responded / n_sent if n_sent else 0.0

# Count prompts after burn-in
post_burn = dec_df[dec_df["day"] >= burn_in]
prompts_sent = int(post_burn["send_prompt"].sum())
# Normalize to per-week; burn-in reduces the active window
weeks = (days - burn_in) / 7.0
prompts_per_week = prompts_sent / weeks if weeks > 0 else 0.0
projected = _grid_projection(threshold_q, burn_in)

rho_err = abs(rho_hat - true_rho) if not np.isnan(rho_hat) else float("nan")
sigma_err = abs(sigma_hat - true_sigma) if not np.isnan(sigma_hat) else float("nan")

st.title(f"JITAI : Single User ({days}-day simulation)")
st.caption(
    f"Seed {seed} · {days}d · {ema_per_day} EMA/day · "
    f"resp_rate {resp_rate:.0%} · MSSD threshold {threshold_q:.0%} · burn-in {burn_in}d"
)

#
tab_overview, tab_ema, tab_wearable, tab_decisions, tab_user = st.tabs(
    ["Overview", "EMA / Affect", "Wearable Telemetry", "JITAI Decisions", "User Profile"]
)



with tab_overview:
    st.subheader("Summary metrics")

    c1, c2, c3, c4 = st.columns(4)
    c1.metric(
        "EMA response rate",
        f"{actual_rr:.1%}",
        delta=f"{actual_rr - 0.70:+.1%} vs 70% target",
        delta_color="normal",
    )
    c2.metric(
        "Prompts / week (post burn-in)",
        f"{prompts_per_week:.1f}",
        delta=f"{prompts_per_week - projected:+.1f} vs grid ({projected:.1f})",
        delta_color="off",
        help=f"Sensitivity-grid projection at {threshold_q:.0%} threshold, "
             f"burn-in={burn_in}d, resp_rate=80% (fixed reference).",
    )
    c3.metric(
        "ρ̂ recovery error",
        f"{rho_err:.3f}" if not np.isnan(rho_err) else "n/a",
        help=f"True ρ = {true_rho:.3f} · Recovered ρ̂ = {rho_hat:.3f}",
    )
    c4.metric(
        "σ̂ recovery error",
        f"{sigma_err:.3f}" if not np.isnan(sigma_err) else "n/a",
        help=f"True σ = {true_sigma:.3f} · Recovered σ̂ = {sigma_hat:.3f}",
    )

    st.caption(
        f"Ground truth : σ: {true_sigma:.3f} · ρ: {true_rho:.3f} · "
        f"Expected MSSD: {true_mssd:.3f} · Empirical MSSD: {emp_mssd:.3f}"
    )

    st.divider()

    view_options = ["Single day", "7 days", "Full study"]
    # Only show "7 days" if the study is actually longer than 7 days
    if days <= 7:
        view_options = ["Single day", "Full study"]
    sel_col, day_col = st.columns([2, 2])
    timeline_view = sel_col.selectbox("Timeline window", view_options, index=len(view_options) - 1)

    # Build full timeline indexed on timestamp
    timeline = dec_df[["timestamp", "day", "ema", "observed_mssd", "user_threshold", "send_prompt"]].copy()
    timeline["timestamp"] = pd.to_datetime(timeline["timestamp"])
    timeline = timeline.sort_values("timestamp")

    if timeline_view == "Single day":
        available_days = sorted(timeline["day"].unique().tolist())
        selected_day = day_col.selectbox("Day", available_days, format_func=lambda d: f"Day {d + 1}")
        view_df = timeline[timeline["day"] == selected_day]
        window_label = f"Day {selected_day + 1}"
    elif timeline_view == "7 days":
        view_df = timeline[timeline["day"] < 7]
        window_label = "Days 1–7"
    else:
        view_df = timeline
        window_label = f"Full study ({days}d)"

    st.subheader(f"Timeline — {window_label}")

    chart_df = view_df.set_index("timestamp")[["ema", "observed_mssd", "user_threshold"]]
    triggers_view = view_df[view_df["send_prompt"] == True]
    st.line_chart(chart_df, height=340)

    if not triggers_view.empty:
        st.caption(
            f"**{len(triggers_view)} prompt trigger(s)** in this window — "
            "MSSD crossed the within-person threshold. "
            "EMA gaps (NaN) appear as breaks in the EMA trace."
        )
    else:
        st.caption("No prompts triggered in this window. Try lowering the threshold percentile.")

    st.divider()
    st.subheader("Parameter recovery")

    rec_df = pd.DataFrame({
        "Parameter": ["σ (volatility)", "ρ (autocorrelation)", "Expected MSSD"],
        "True value": [f"{true_sigma:.3f}", f"{true_rho:.3f}", f"{true_mssd:.3f}"],
        "Recovered": [
            f"{sigma_hat:.3f}" if not np.isnan(sigma_hat) else ":",
            f"{rho_hat:.3f}" if not np.isnan(rho_hat) else ":",
            f"{emp_mssd:.3f}" if not np.isnan(emp_mssd) else ":",
        ],
        "Abs error": [
            f"{sigma_err:.3f}" if not np.isnan(sigma_err) else ":",
            f"{rho_err:.3f}" if not np.isnan(rho_err) else "—",
            f"{abs(emp_mssd - true_mssd):.3f}" if not np.isnan(emp_mssd) else "—",
        ],
    })
    st.dataframe(rec_df, use_container_width=True, hide_index=True)



with tab_ema:
    st.subheader("EMA time series and decision engine")

    left, right = st.columns(2)

    with left:
        st.markdown("#### EMA observations")
        ema_plot = dec_df[["timestamp", "ema", "observed_mssd", "user_threshold"]].copy()
        ema_plot["timestamp"] = pd.to_datetime(ema_plot["timestamp"])
        ema_plot = ema_plot.set_index("timestamp")
        st.line_chart(ema_plot, height=320)
        st.caption(
            "EMA values (1–5 Likert). Gaps = missing responses. "
            "MSSD and threshold accrue from answered observations only."
        )

    with right:
        st.markdown("#### Decision reason breakdown")
        reason_counts = (
            dec_df["decision_reason"]
            .fillna("missing reason")
            .value_counts()
            .rename_axis("decision_reason")
            .reset_index(name="count")
        )
        st.bar_chart(
            reason_counts.set_index("decision_reason"),
            horizontal=True,
            height=320,
        )
        st.caption(f"Total decision records: {len(dec_df):,}")

    st.divider()
    st.subheader("Decision history")

    history_cols = ["timestamp", "ema", "observed_mssd", "user_threshold",
                    "send_prompt", "decision_reason"]
    history = dec_df[[c for c in history_cols if c in dec_df.columns]].copy()
    history["timestamp"] = pd.to_datetime(history["timestamp"])
    st.dataframe(history.sort_values("timestamp"), use_container_width=True, hide_index=True)



with tab_wearable:
    st.subheader("Heart rate (minute-level)")

    # Decimate to 5-min means for rendering performance (10,080 → ~2,016 pts)
    hr_plot = hr_df.copy()
    hr_plot["timestamp"] = pd.to_datetime(hr_plot["timestamp"])
    hr_plot = (
        hr_plot.set_index("timestamp")
        .resample("5min")[["hr", "stress", "rmssd_ms"]]
        .mean()
    )

    st.line_chart(hr_plot[["hr"]], height=220)
    st.caption("5-minute means. Circadian rhythm (trough ~4 am, peak ~4 pm) plus random activity bouts.")

    st.subheader("Stress and continuous HRV (RMSSD)")
    st.line_chart(hr_plot[["stress", "rmssd_ms"]], height=220)
    st.caption(
        "Stress (0–100): normalized from HR band 55–130 bpm. "
        "RMSSD (ms): beat-to-beat HRV estimated from simulated RR intervals."
    )

    st.divider()
    st.subheader("Overnight HRV status")

    hrv_plot = hrv_df[["night", "overnight_avg_rmssd", "baseline_7d", "hrv_status"]].copy()
    hrv_plot["night"] = pd.to_datetime(hrv_plot["night"])
    hrv_plot = hrv_plot.sort_values("night").set_index("night")

    # Color map for status labels (shown as caption; bar chart uses default colors)
    status_order = hrv_plot["hrv_status"].tolist()
    rmssd_chart = hrv_plot[["overnight_avg_rmssd", "baseline_7d"]]
    st.line_chart(rmssd_chart, height=220)
    st.caption(
        "Overnight RMSSD vs 7-night rolling baseline. "
        "Status labels: " + " · ".join(
            f"Night {i+1}: **{s}**" for i, s in enumerate(status_order)
        )
    )

    if all(s == "No Status" for s in status_order):
        st.info(
            "All nights show 'No Status' - the 7-night baseline window hasn't filled yet "
            "in a 7-day simulation. This is expected behaviour; real studies run 28+ days."
        )

    st.divider()
    st.subheader("Daily load (stress z-score)")

    load_chart = load_df[["day", "load_z"]].set_index("day")
    st.bar_chart(load_chart, height=200)
    st.caption(
        "Per-day mean stress z-scored within this participant. "
        "Positive = high-load day → lower overnight RMSSD the following night."
    )

with tab_decisions:
    st.subheader("Prompts sent per day")

    daily_prompts = (
        dec_df[dec_df["send_prompt"] == True]
        .assign(date=lambda d: pd.to_datetime(d["timestamp"]).dt.date)
        .groupby("date")["send_prompt"]
        .sum()
        .rename("prompts_sent")
        .reset_index()
        .set_index("date")
    )

    if daily_prompts.empty:
        st.info("No prompts were triggered. Lower the threshold percentile to see prompts.")
    else:
        st.bar_chart(daily_prompts, height=260)
        st.caption(
            f"Daily cap: 4 prompts/day · 60-min cooldown · "
            f"burn-in {burn_in}d (no prompts counted during warm-up)."
        )

    st.divider()
    st.subheader("Decision reasons per day")

    dec_df_copy = dec_df.copy()
    dec_df_copy["date"] = pd.to_datetime(dec_df_copy["timestamp"]).dt.date
    reason_daily = (
        dec_df_copy.groupby(["date", "decision_reason"])
        .size()
        .reset_index(name="count")
        .pivot(index="date", columns="decision_reason", values="count")
        .fillna(0)
    )
    st.bar_chart(reason_daily, height=300)
    st.caption("Each bar shows the count of decisions per reason per day.")

    st.divider()
    st.subheader("Full decision log")

    log_cols = ["timestamp", "day", "ema", "observed_mssd",
                "user_threshold", "send_prompt", "decision_reason"]
    full_log = dec_df[[c for c in log_cols if c in dec_df.columns]].copy()
    full_log["timestamp"] = pd.to_datetime(full_log["timestamp"])
    st.dataframe(
        full_log.sort_values("timestamp"),
        use_container_width=True,
        hide_index=True,
    )

    with st.expander("Raw DataFrames"):
        st.markdown("#### EMA DataFrame")
        st.dataframe(ema_df, use_container_width=True, hide_index=True)
        st.markdown("#### HR DataFrame (first 500 rows)")
        st.dataframe(hr_df.head(500), use_container_width=True, hide_index=True)
        st.markdown("#### HRV Status")
        st.dataframe(hrv_df, use_container_width=True, hide_index=True)
        st.markdown("#### Daily Load")
        st.dataframe(load_df, use_container_width=True, hide_index=True)



with tab_user:
    user_id = str(dec_df["user_id"].iloc[0])
    profile = build_user_profile(user_id, seed, hr_df, hrv_df)

    st.subheader("User record")
    st.caption(
        "Fields match the app schema (`user` + `wearable_device` tables). "
        "`push_token` and `password` are excluded — not generated by the simulator."
    )

    st.markdown("#### Identity")
    id_cols = st.columns(3)
    id_cols[0].text_input("user_id", value=profile["user_id"], disabled=True)
    id_cols[1].text_input("first_name", value=profile["first_name"], disabled=True)
    id_cols[2].text_input("last_name", value=profile["last_name"], disabled=True)

    id_cols2 = st.columns(3)
    id_cols2[0].text_input("email", value=profile["email"], disabled=True)
    id_cols2[1].text_input("birthdate", value=profile["birthdate"], disabled=True)
    id_cols2[2].text_input("gender", value=profile["gender"], disabled=True)

    enr_cols = st.columns(3)
    enr_cols[0].text_input("is_enrolled", value=str(profile["is_enrolled"]), disabled=True)
    enr_cols[1].text_input("enrolled_at", value=profile["enrolled_at"], disabled=True)

    st.divider()

    # ── Wearable device ─────────────────────────────────────────────────────
    st.markdown("#### Wearable device (`wearable_device` table)")
    dev_cols = st.columns(3)
    dev_cols[0].text_input("labfront_participant_id",
                           value=profile["labfront_participant_id"], disabled=True)
    dev_cols[1].text_input("device_model", value=profile["device_model"], disabled=True)
    dev_cols[2].text_input("is_active", value=str(profile["device_is_active"]), disabled=True)
    st.text_input("last_synced_at", value=profile["last_synced_at"], disabled=True)

    st.divider()

    # ── Simulation parameters (latent, ground-truth) ────────────────────────
    st.markdown("#### Simulation parameters *(ground-truth — not in real schema)*")
    st.caption(
        "These are the latent AR(1) parameters drawn for this participant. "
        "In a real study these are unknown; the decision engine estimates them from responses."
    )

    sim_cols = st.columns(4)
    sim_cols[0].metric("True σ (volatility)", f"{true_sigma:.3f}")
    sim_cols[1].metric("True ρ (autocorrelation)", f"{true_rho:.3f}")
    sim_cols[2].metric("Expected MSSD", f"{true_mssd:.3f}")
    sim_cols[3].metric(
        "Est. resting HR",
        f"{profile['sim_resting_hr_est']} bpm" if profile["sim_resting_hr_est"] else "—",
        help="5th-percentile of minute-level HR over 7 days (proxy for resting HR).",
    )

    sim_cols2 = st.columns(4)
    sim_cols2[0].metric(
        "Overnight RMSSD baseline",
        f"{profile['sim_baseline_rmssd']} ms" if profile["sim_baseline_rmssd"] else "No Status",
        help="Mean of available 7-night trailing baseline values.",
    )
    sim_cols2[1].metric("Recovered ρ̂", f"{rho_hat:.3f}" if not np.isnan(rho_hat) else "—")
    sim_cols2[2].metric("Recovered σ̂", f"{sigma_hat:.3f}" if not np.isnan(sigma_hat) else "—")
    sim_cols2[3].metric("Empirical MSSD", f"{emp_mssd:.3f}" if not np.isnan(emp_mssd) else "—")

    st.divider()

    # ── Flat schema table ────────────────────────────────────────────────────
    st.markdown("#### Full record as table")
    schema_rows = [
        {"Table": "user", "Column": "user_id",       "Value": profile["user_id"],       "Type": "INT (PK)"},
        {"Table": "user", "Column": "email",          "Value": profile["email"],          "Type": "VARCHAR(254)"},
        {"Table": "user", "Column": "first_name",     "Value": profile["first_name"],     "Type": "VARCHAR(100)"},
        {"Table": "user", "Column": "last_name",      "Value": profile["last_name"],      "Type": "VARCHAR(100)"},
        {"Table": "user", "Column": "birthdate",      "Value": profile["birthdate"],      "Type": "DATE"},
        {"Table": "user", "Column": "gender",         "Value": profile["gender"],         "Type": "VARCHAR(10)"},
        {"Table": "user", "Column": "password",       "Value": "— not generated —",      "Type": "VARCHAR(128)"},
        {"Table": "user", "Column": "push_token",     "Value": "— not generated —",      "Type": "VARCHAR(128)"},
        {"Table": "user", "Column": "is_enrolled",    "Value": str(profile["is_enrolled"]), "Type": "BOOLEAN"},
        {"Table": "user", "Column": "enrolled_at",    "Value": profile["enrolled_at"],    "Type": "DATETIME"},
        {"Table": "wearable_device", "Column": "labfront_participant_id",
                                     "Value": profile["labfront_participant_id"], "Type": "VARCHAR(64)"},
        {"Table": "wearable_device", "Column": "device_model",
                                     "Value": profile["device_model"],           "Type": "VARCHAR(32)"},
        {"Table": "wearable_device", "Column": "is_active",
                                     "Value": str(profile["device_is_active"]),  "Type": "BOOLEAN"},
        {"Table": "wearable_device", "Column": "last_synced_at",
                                     "Value": profile["last_synced_at"],         "Type": "DATETIME"},
        {"Table": "sim (latent)",    "Column": "true_sigma",
                                     "Value": f"{true_sigma:.4f}",               "Type": "FLOAT"},
        {"Table": "sim (latent)",    "Column": "true_rho",
                                     "Value": f"{true_rho:.4f}",                 "Type": "FLOAT"},
        {"Table": "sim (latent)",    "Column": "true_expected_mssd",
                                     "Value": f"{true_mssd:.4f}",               "Type": "FLOAT"},
    ]
    st.dataframe(pd.DataFrame(schema_rows), use_container_width=True, hide_index=True)

    st.divider()
    st.subheader("User Assumptions")
    st.caption("Generative models underlying this participant's synthetic data.")

    # ── EMA / Affect ────────────────────────────────────────────────────────
    st.markdown("**EMA / Affect**")
    st.latex(
        r"z_t = \rho \, z_{t-1} + \varepsilon_t, "
        r"\quad \varepsilon_t \sim \mathcal{N}\!\left(0,\; \sigma^2(1 - \rho^2)\right)"
    )
    st.latex(
        r"\text{EMA}_t = \text{clip}\!\left(\text{round}(\mu + z_t),\; 1,\; 5\right)"
    )
    st.latex(
        r"\mu \sim \mathcal{U}(2,\,4), "
        r"\quad \sigma \sim \mathcal{U}(0.3,\,1.5), "
        r"\quad \rho \sim \mathcal{U}(0.1,\,0.8)"
    )
    st.markdown(
        "Missingness: 2-state Markov chain with transition probabilities tuned to "
        "`resp_rate` and `mean_gap_length = 3`."
    )

    # ── Heart Rate & Stress ─────────────────────────────────────────────────
    st.markdown("**Heart Rate & Stress**")
    st.latex(
        r"\mathrm{HR}[t] = \mathrm{HR}_{\text{rest}} + \mathrm{circ}(t) "
        r"+ \mathcal{N}(0,\,2) + \mathrm{bouts}(t)"
    )
    st.latex(r"\mathrm{HR}_{\text{rest}} \sim \mathcal{U}(60,\,100)\;\text{bpm}")
    st.latex(
        r"\text{Stress}[t] = \text{clip}\!\left("
        r"100 \cdot \frac{\mathrm{HR}[t] - 55}{130 - 55} + \mathcal{N}(0,\,4),\;"
        r"0,\;100\right)"
    )
    st.markdown(
        "Circadian amplitude: ±6 bpm (trough 4 am, peak 4 pm). "
        "Activity bouts: 0–3/day, 20–60 min each, +15–40 bpm. "
        "RMSSD: estimated from beat-by-beat RR intervals simulated per minute."
    )

    # ── Overnight HRV ───────────────────────────────────────────────────────
    st.markdown("**Overnight HRV**")
    st.latex(
        r"z_d^{\text{night}} = \varphi \, z_{d-1}^{\text{night}} + \eta_d, "
        r"\quad \eta_d \sim \mathcal{N}\!\left(0,\;\sigma_n^2(1-\varphi^2)\right), "
        r"\quad \varphi = 0.5,\;\sigma_n = 6\;\text{ms}"
    )
    st.latex(
        r"\mathrm{RMSSD}_d = \text{baseline} + z_d^{\text{night}} "
        r"- \lambda \cdot \mathrm{load}_z[d] + \mathcal{N}(0,\,4), "
        r"\quad \lambda = 5\;\text{ms/SD}"
    )
    st.markdown(
        "Baseline = 7-night trailing mean of overnight RMSSD. "
        "Status labels: Balanced / Low / Unbalanced / No Status (first 7 nights)."
    )

    # ── Decision Engine ─────────────────────────────────────────────────────
    st.markdown("**Decision Engine**")
    st.latex(
        r"\mathrm{MSSD}_t = \frac{1}{w} \sum_{k=0}^{w-1} "
        r"\left(\mathrm{EMA}_{t-k} - \mathrm{EMA}_{t-k-1}\right)^2, "
        r"\quad w = 3"
    )
    st.latex(
        r"\text{send prompt} \iff "
        r"\mathrm{MSSD}_t > Q_{0.80}^{\text{within-person}} "
        r"\;\land\; \Delta t_{\text{last}} > 60\;\text{min} "
        r"\;\land\; n_{\text{day}} < 4"
    )
    st.warning(
        "**MSSD gap limitation:** successive differences are computed row-by-row "
        "(`EMA[t] - EMA[t-1]`). If either observation is missing, the difference "
        r"is undefined (NaN), so $\mathrm{MSSD}_t$ is also NaN at that row *and* "
        "at the immediately following row (the 'bridge' after a gap is lost too). "
        "A rolling window of 3 can carry a non-NaN value one or two rows into a gap, "
        "but extended missing streaks suppress MSSD entirely. "
        "The decision engine additionally skips any row where EMA is NaN, regardless "
        "of whether a carry-forward MSSD exists. "
        "**Consequence:** if missingness is highest when stress is highest (MNAR), "
        "volatility is systematically undercounted in exactly those moments."
    )
